spring:
  datasource:
    url: jdbc:mysql://115.159.154.194:3306/police_support_platform?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: qunchuang@2020

server:
  servlet:
    context-path: /modeler
  port: 8030