spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/police_support_platform?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    schema: classpath:sql/schema.sql
    initialization-mode: always # 暂时禁用JPA 通过脚本启动
flowable:
  common:
    app:
      idm-url: test # 目前没什么作用,则伪造了一个 idm 访问的 url
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: admin
        last-name: admin
mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  config-location: classpath:/META-INF/mybatis-config.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
server:
  servlet:
    context-path: /modeler
  port: 9090
