spring:
  datasource:
    url: jdbc:h2:file:./db/flowable-modeler
    initialization-mode: always # 暂时禁用JPA 通过脚本启动
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
flowable:
  common:
    app:
      idm-url: test # 目前没什么作用,则伪造了一个 idm 访问的 url
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: admin
        last-name: admin
mybatis:
  mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
  config-location: classpath:/META-INF/mybatis-config.xml
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
server:
  servlet:
    context-path: /modeler
  port: 9090